{
 "title": "New dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Filesystem",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"grafana-server\",mountpoint=\"/\"}"
    },
    {
     "expr": "node_filesystem_avail_bytes{job=\"grafana-server\",mountpoint=\"/\"}"
    }
   ]
  },
  {
   "title": "Memory free",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{job=\"grafana-server\"}"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg by (instance)(rate(node_load1{job=\"grafana-server\"}[$__rate_interval]))"
    },
    {
     "expr": "avg by (instance)(rate(node_load5{job=\"grafana-server\"}[$__rate_interval]))"
    },
    {
     "expr": "avg by (instance)(rate(node_load15{job=\"grafana-server\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "утилизация CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "avg by(instance)(rate(node_cpu_seconds_total{job=\"grafana-server\",mode=\"idle\"}[$__rate_interval])) * 100"
    }
   ]
  }
 ]
}