version: '3.9'
services:

  elasticsearch:
    image: elasticsearch:7.14.2
    container_name: elasticsearch
    environment:
      - node.name=netology_test
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - es-data:/var/lib/es-data
    networks:
      - elasticsearch-net
    ports:
      - 9200:9200
      - 9300:9300
    restart: always

  kibana:
    depends_on:
      - elasticsearch
    image: kibana:7.14.2
    container_name: kibana
    environment:
      - ELACTICSEARCH_HOSTS=http://elasticsearch:9200
    volumes:
      - kb-data:/var/lib/kb-data
    networks:
      - elasticsearch-net
    ports:
      - 5601:5601
    restart: always

networks:
  elasticsearch-net:
    driver: bridge

volumes:
  es-data:
    driver: local
  kb-data:
    driver: local
