version: "3"
services:
  teamcity-server:
    restart: always
    image: jetbrains/teamcity-server
    volumes:
      - ~/teamcity/data/:/data/teamcity_server/datadir
      - ~/teamcity/logs/:/opt/teamcity/logs
    ports:
      - 8111:8111
