---
all:
  hosts:
    teamcity-server:
      ansible_host: 84.201.157.247
    teamcity-agent:
      ansible_host: 51.250.91.154
    nexus-01:
      ansible_host: 51.250.67.89
  children:
    teamcity:
      hosts:
        teamcity-server:
        teamcity-agent:
    nexus:
      hosts:
        nexus-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: sergo