---
all:
  hosts:
    grafana-server:
      ansible_host: 158.160.110.34
    node-01:
      ansible_host: 51.250.79.189
    node-02:
      ansible_host: 158.160.109.16
  children:
    server:
      hosts:
        grafana-server:
    metrics:
      hosts:
        grafana-server:
        node-01:
        node-02:
  vars:
    ansible_connection_type: paramiko
    ansible_user: sergo
