apiVersion: v1
kind: Service
metadata:
  name: deployment-svc
spec:
  selector:
    app: multitool
  ports:
  - name: fo-nginx
    port: 80
    targetPort: 80
  - name: for-multitool
    port: 8080
    targetPort: 8080
